Repository 772-company/kkom-kkom, pull requests merged in 2024-09, with the labels that each got.

#305 fix:utc 시간 설정 문제
  app/[groupId]/tasks/_components/comment/comment.tsx
  app/[groupId]/tasks/_components/modal/add-todo-modal/index.tsx
  app/[groupId]/tasks/_components/side-bar.tsx
  app/[groupId]/tasks/_components/todo/kebab-popover.tsx
  app/[groupId]/tasks/_components/todo/todo-box.tsx
  app/[groupId]/tasks/_components/todo/todo-contents.tsx
  app/[groupId]/tasks/_hooks/use-calendar.ts
  lib/apis/task/hooks/use-post-task.ts
  lib/apis/task/index.ts
Labels: 🐛 fix

#303 refactor: 할 일 목록 삭제 낙관적 업데이트 적용
  app/[groupId]/_components/modal/modal-task-list-delete.tsx
Labels: ♻️ refactor

#309 fix: 자유게시판 게시글, 댓글 관련 로직, 이미지 에러 처리
  app/(free-board)/_components/card.tsx
  app/(free-board)/_query/mutation.ts
  app/(free-board)/boards/[boardId]/_components/comment-card.tsx
  app/(free-board)/boards/[boardId]/_components/comments-list.tsx
  components/intersection-area/intersection-area.tsx
Labels: 🐛 fix

#311 fix: 댓글 삭제시 해당 게시글 쿼리 초기화
  app/(free-board)/_query/mutation.ts
Labels: 🐛 fix

#297 docs: README 작성
  README.md
  image.png
Labels: 📝 docs

#312 fix: robots.txt 정적파일로 변경
  app/robot.ts
  public/robots.txt
Labels: 🐛 fix

#313 feat: GA/ GTM 연결
  app/(free-board)/boards/[boardId]/page.tsx
  app/layout.tsx
  components/gtm/gtm-page-view.tsx
  lib/gtm/declaration.d.ts
  lib/gtm/index.ts
  package.json
  pnpm-lock.yaml
Labels: ✨ feat

#315 docs: gif 추가
  README.md
Labels: 📝 docs

#317 fix: 모든 멤버의 프로필 모달에 왕관 달아주는 버그 수정
  app/[groupId]/_components/member-list.tsx
  app/[groupId]/_components/modal/modal-member-profile.tsx
  app/[groupId]/_components/modal/modal-task-list-name-edit.tsx
Labels: 🐛 fix

#319 fix: storybook global.css 관련 오류 수정
  .storybook/preview.ts
Labels: 🐛 fix

#321 docs: 리드미 수정
  README.md
Labels: 📝 docs
