Repository 772-company/kkom-kkom, pull requests merged in 2024-07, with the labels that each got.

#2 chore : PR, issue 템플릿 추가 ( pull request 예시입니다. )
  .github/ISSUE_TEMPLATE/💄-ui.md
Labels: 📦 chore

#7 chore : 프로젝트 기본 세팅, CICD 설정
  .github/workflows/vercel-merge.yml
  .github/workflows/vercel-pull-request.yml
  app/page.tsx
  package.json
Labels: 📦 chore

#9 feat: 드롭다운 컴포넌트 생성
  app/test/page.tsx
  components/dropdown/body.tsx
  components/dropdown/button.tsx
  components/dropdown/dropdown.tsx
  components/dropdown/item.tsx
  hooks/use-click-outside.ts
Labels: ✨ feat

#11 chore: svgr 라이브러리 설치
  app/test/svg/page.tsx
  global.d.ts
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/user.svg
  tsconfig.json
Labels: 📦 chore

#18 chore: tailwind css 커스텀 컬러 설정
  app/page.tsx
  tailwind.config.ts
Labels: 📦 chore

#17 chore : 폴더 구조 세팅 및 api res 타입 세팅
  components/.gitkeep
  constants/.gitkeep
  hooks/.gitkeep
  lib/apis/index.ts
  lib/apis/type/index.ts
  public/fonts/.gitkeep
  public/icons/.gitkeep
  public/images/.gitkeep
  public/next.svg
  public/vercel.svg
  styles/.gitkeep
  utils/.gitkeep
Labels: 📦 chore

#23 refactor: 드롭다운 컴포넌트 하나로 병합
  components/dropdown/body.tsx
  components/dropdown/button.tsx
  components/dropdown/dropdown.tsx
  components/dropdown/item.tsx
Labels: ♻️ refactor

#25 chore: 아이콘 파일 첨부
  app/public/fonts/.gitkeep
  app/public/icons/alert.svg
  app/public/icons/arrow-left.svg
  app/public/icons/arrow-right.svg
  app/public/icons/calendar.svg
  app/public/icons/check-wide.svg
  app/public/icons/check.svg
  app/public/icons/checkbox-active.svg
  app/public/icons/checkbox-default.svg
  app/public/icons/comment.svg
  app/public/icons/done.svg
  app/public/icons/gear.svg
  app/public/icons/img.svg
  app/public/icons/kebab-large.svg
  app/public/icons/kebab-small.svg
  app/public/icons/list.svg
  app/public/icons/plus.svg
  app/public/icons/progress-done.svg
  app/public/icons/progress-ongoing.svg
  app/public/icons/repair.svg
  app/public/icons/toggle.svg
  app/public/icons/user.svg
  app/public/icons/visibility-off.svg
  app/public/icons/visibility-on.svg
  app/public/icons/x.svg
  app/public/images/.gitkeep
  app/test/svg/page.tsx
  public/icons/.gitkeep
  public/images/.gitkeep
Labels: 📦 chore

#26 chore: 스토리북 세팅
  .eslintrc.json
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  pnpm-lock.yaml
  stories/Button.stories.ts
  stories/Button.tsx
  stories/Configure.mdx
  stories/Header.stories.ts
  stories/Header.tsx
  stories/Page.stories.ts
  stories/Page.tsx
  stories/assets/accessibility.png
  stories/assets/accessibility.svg
  stories/assets/addon-library.png
  stories/assets/assets.png
  stories/assets/avif-test-image.avif
  stories/assets/context.png
  stories/assets/discord.svg
  stories/assets/docs.png
  stories/assets/figma-plugin.png
  stories/assets/github.svg
  stories/assets/share.png
  stories/assets/styling.png
  stories/assets/testing.png
  stories/assets/theming.png
  stories/assets/tutorials.svg
  stories/assets/youtube.svg
  stories/button.css
  stories/header.css
  stories/page.css
Labels: 📦 chore

#28 feat: 버튼 컴포넌트 구현
  .storybook/preview.ts
  app/layout.tsx
  app/test/page.tsx
  components/button/Icon-button.tsx
  components/button/index.tsx
  package-lock.json
  public/hamster.jpg
  stories/Button.stories.ts
  styles/.gitkeep
  styles/globals.css
Labels: ✨ feat

#20 feat: 팝오버 컴포넌트 생성
  app/page.tsx
  components/popover.tsx
  package.json
  pnpm-lock.yaml
Labels: ✨ feat

#34 feat: 공통컴퍼넌트 프로필 인풋 팀프로필 인풋 구현
  app/public/icons/my-profile.svg
  app/test2/page.tsx
  components/profile-input/profile-input.tsx
  tsconfig.json
Labels: ✨ feat

#38 feat: 공통 인풋 컴포넌트 구현
  app/public/images/.gitkeep
  app/test/page.tsx
  components/input-field/basic-input.tsx
  components/input-field/password-input.tsx
  components/profile-input/profile-input.tsx
  package-lock.json
  package.json
  pnpm-lock.yaml
  public/fonts/.gitkeep
  public/icons/alert.svg
  public/icons/arrow-left.svg
  public/icons/arrow-right.svg
  public/icons/calendar.svg
  public/icons/check-wide.svg
  public/icons/check.svg
  public/icons/checkbox-active.svg
  public/icons/checkbox-default.svg
  public/icons/comment.svg
  public/icons/done.svg
  public/icons/eye-off.svg
  public/icons/eye-on.svg
  public/icons/gear.svg
  public/icons/img.svg
  public/icons/kebab-large.svg
  public/icons/kebab-small.svg
  public/icons/list.svg
  public/icons/my-profile.svg
  public/icons/plus.svg
  public/icons/progress-done.svg
  public/icons/progress-ongoing.svg
  public/icons/repair.svg
  public/icons/toggle.svg
  public/icons/user.svg
  public/icons/x.svg
  public/images/hamster.jpg
  tailwind.config.ts
Labels: ✨ feat

#31 feat: zustand 세팅
  app/layout.tsx
  app/test/page.tsx
  package.json
  pnpm-lock.yaml
  providers/modal-store-provider.tsx
  stores/modal-store.ts
Labels: ✨ feat

#42 refactor: 라벨 색상 추가 및 모달일 때 간격 조정
  components/input-field/basic-input.tsx
Labels: ♻️ refactor

#44 feat: 비밀번호 변경하기 input 컴포넌트 구현
  app/test/page.tsx
  components/input-field/basic-input.tsx
  components/input-field/password-input.tsx
Labels: ✨ feat

#47 feat: button_floating 컴포넌트 구현
  app/test/page.tsx
  components/button-floating/index.tsx
  public/icons/check.svg
  stories/ButtonFloating.stories.ts
Labels: ✨ feat

#43 feat: toast 컴포넌트 구현
  app/layout.tsx
  app/test/page.tsx
  lib/show-toast/index.tsx
  package.json
  pnpm-lock.yaml
  providers/toast-provider.tsx
Labels: ✨ feat

#49 feat: 로그인 전 헤더 컴포넌트 구현
  app/layout.tsx
  components/header/header.tsx
  components/header/login-button.tsx
  public/icons/logo.svg
Labels: ✨ feat

#51 refactor: 공통 버튼 컴포넌트
  components/button/index.tsx
  components/button/schema/index.ts
  package.json
  pnpm-lock.yaml
Labels: ♻️ refactor

#52 feat: preview 이미지가 있을 때 x버튼 로직 구현
  app/test2/page.tsx
  components/profile-input/profile-input.tsx
Labels: ✨ feat

#53 feat: button_floating 스토리북 적용
  .storybook/main.ts
  app/page.tsx
  app/test/page.tsx
  components/button-floating/button-floating.tsx
  components/popover/popover.tsx
  stories/Button.stories.ts
  stories/ButtonFloating.stories.ts
Labels: ✨ feat

#61 design: 로그인 페이지 UI 구현
  app/(auth)/login/page.tsx
  app/(auth)/signin/.gitkeep
  app/layout.tsx
  components/input-field/basic-input.tsx
  public/icons/google.svg
  public/icons/kakao-talk.svg
  schemas/auth.ts
Labels: 💄design

#36 feat : 공통 모달 컴포넌트 구현
  app/(auth)/login/page.tsx
  app/test/page.tsx
  components/button-floating/button-floating.tsx
  components/button/button.tsx
  components/button/variants/index.ts
  components/input-field/password-input.tsx
  components/modal/components/one-button-section.tsx
  components/modal/components/two-button-section.tsx
  components/modal/modal-danger.tsx
  components/modal/modal-detailed-one-button.tsx
  components/modal/modal-detailed-two-button.tsx
  components/modal/modal-one-button.tsx
  components/modal/modal-two-button.tsx
  components/modal/modal-warning.tsx
  components/modal/modal.tsx
  components/modal/popup-one-button.tsx
  pnpm-lock.yaml
  stories/Button.stories.ts
Labels: ✨ feat

#56 fix: 버튼위치 및 css 오타 수정
  components/profile-input/profile-input.tsx
Labels: 🐛 fix
