Repository 772-company/kkom-kkom, pull requests merged in 2024-08, with the labels that each got.

#63 feat: 팀 페이지-현재 팀 나타내는 컴포넌트
  app/[teamId]/_components/fetch-data.tsx
  app/[teamId]/_components/team.tsx
  app/[teamId]/page.tsx
  components/popover/popover.tsx
  public/images/thumbnail-team.png
Labels: ✨ feat

#69 feat: 로그인 기능 구현
  app/(auth)/_components/easy-login-button.tsx
  app/(auth)/_components/easy-login.tsx
  app/(auth)/layout.tsx
  app/(auth)/login/_components/login-form.tsx
  app/(auth)/login/page.tsx
  app/(auth)/signin/.gitkeep
  app/(auth)/signup/page.tsx
  app/layout.tsx
  components/input-field/basic-input.tsx
  lib/apis/auth/index.ts
  lib/apis/type/index.ts
  lib/apis/user/index.ts
  package.json
  pnpm-lock.yaml
Labels: ✨ feat

#68 feat: 팀 페이지 - 할 일 목록 컴포넌트
  app/[teamId]/_components/task-lists.tsx
  app/[teamId]/page.tsx
  lib/apis/group/index.ts
  lib/apis/type/index.ts
Labels: ✨ feat

#67 chore: 앱 디렉토리 세팅
  app/(auth)/login/layout.tsx
  app/(auth)/reset-password/layout.tsx
  app/(auth)/reset-password/page.tsx
  app/(auth)/signup/layout.tsx
  app/(free-board)/addboard/layout.tsx
  app/(free-board)/addboard/page.tsx
  app/(free-board)/board/[boardId]/layout.tsx
  app/(free-board)/board/[boardId]/page.tsx
  app/(free-board)/boards/layout.tsx
  app/(free-board)/boards/page.tsx
  app/(free-board)/layout.tsx
  app/(team-setting)/addteam/layout.tsx
  app/(team-setting)/addteam/page.tsx
  app/(team-setting)/layout.tsx
  app/(team-setting)/participate-team/layout.tsx
  app/(team-setting)/participate-team/page.tsx
  app/[teamId]/edit/layout.tsx
  app/[teamId]/edit/page.tsx
  app/[teamId]/layout.tsx
  app/[teamId]/tasks/layout.tsx
  app/[teamId]/tasks/page.tsx
  app/layout.tsx
  app/myhistory/layout.tsx
  app/myhistory/page.tsx
  app/mypage/layout.tsx
  app/mypage/page.tsx
  app/no-team/layout.tsx
  app/no-team/page.tsx
  app/test/page.tsx
  app/test2/page.tsx
  components/header/header.tsx
  tailwind.config.ts
Labels: 📦 chore

#71 feat: 회원가입 기능 구현
  app/(auth)/.gitkeep
  app/(auth)/_components/easy-auth.tsx
  app/(auth)/login/_components/login-form.tsx
  app/(auth)/login/page.tsx
  app/(auth)/signup/_components/signup-form.tsx
  app/(auth)/signup/page.tsx
  lib/apis/auth/index.ts
  schemas/auth.ts
Labels: ✨ feat

#72 feat: accessToken 만료 시 refreshToken으로 새로운 토큰 발급 및 로그인 여부에 따른 리다이렉트 구현
  middleware.ts
Labels: ✨ feat

#73 feat: 리스트네임 버튼 구현 및 투두박스 구현
  app/[teamId]/tasks/_components/calendar-button.tsx
  app/[teamId]/tasks/_components/check-button.tsx
  app/[teamId]/tasks/_components/noTodo.tsx
  app/[teamId]/tasks/_components/todo-box-Container.tsx
  app/[teamId]/tasks/_components/todo-box.tsx
  app/[teamId]/tasks/_components/todo-contents.tsx
  app/[teamId]/tasks/_components/todo-contianer.tsx
  app/[teamId]/tasks/_components/todo-header.tsx
  app/[teamId]/tasks/_components/todo-list-name.tsx
  app/[teamId]/tasks/_hooks/use-calendar.ts
  app/[teamId]/tasks/page.tsx
  package.json
  pnpm-lock.yaml
  public/icons/repeat.svg
  public/icons/time.svg
  utils/convert-date.ts
Labels: ✨ feat

#78 feat: 팀 페이지-멤버 목록 컴포넌트
  app/(auth)/layout.tsx
  app/[teamId]/_components/fetch-data.tsx
  app/[teamId]/_components/members.tsx
  app/[teamId]/_components/task-lists.tsx
  app/[teamId]/_components/team.tsx
  app/[teamId]/action.ts
  app/[teamId]/page.tsx
  app/layout.tsx
  components/popover/popover.tsx
  lib/apis/group/index.ts
  lib/apis/type/index.ts
  public/icons/default-profile.svg
Labels: ✨ feat

#81 feat: 로그인 후 헤더 구현
  app/(auth)/login/_components/login-form.tsx
  app/(free-board)/layout.tsx
  app/[teamId]/layout.tsx
  app/action.ts
  app/myhistory/layout.tsx
  app/mypage/layout.tsx
  app/no-team/layout.tsx
  components/button/button.tsx
  components/button/variants/index.ts
  components/dropdown/dropdown.tsx
  components/header/group-dropdown.tsx
  components/header/header.tsx
  components/header/logged-in-header.tsx
  components/header/none-login-header.tsx
  components/header/popover-trigger.tsx
  components/header/side-menu.tsx
  constants/popover-content.ts
  lib/apis/type/index.ts
  lib/apis/user/index.ts
  next.config.mjs
  pnpm-lock.yaml
  public/icons/dropdown-check.svg
  public/icons/gnb-menu.svg
  tailwind.config.ts
Labels: ✨ feat

#80 refactor: 모달 컴포넌트 전역 상태, 애니메이션
  app/layout.tsx
  app/mypage/_component/modal-warning.tsx
  app/mypage/page.tsx
  app/page.tsx
  components/button/button.tsx
  components/button/variants/index.ts
  components/header/components/modal-danger.tsx
  components/modal/components/one-button-section.tsx
  components/modal/components/two-button-section.tsx
  components/modal/modal-detailed-one-button.tsx
  components/modal/modal-detailed-two-button.tsx
  components/modal/modal-one-button.tsx
  components/modal/modal-two-button.tsx
  components/modal/modal-warning.tsx
  components/modal/modal.tsx
  components/modal/popup-one-button.tsx
  components/modal/variants/index.ts
  hooks/use-custom-overlay/index.tsx
  hooks/use-custom-overlay/types/index.ts
  lib/cn/index.ts
  lib/show-toast/index.tsx
  package.json
  pnpm-lock.yaml
  providers/modal-store-provider.tsx
  providers/toast-provider.tsx
  stores/modal-store.ts
  tsconfig.json
Labels: ♻️ refactor

#84 feat: 마이 히스토리 페이지 ui 구현
  app/myhistory/_components/date-box-card.tsx
  app/myhistory/_components/date-box-list-skeleton.tsx
  app/myhistory/_components/date-box-list.tsx
  app/myhistory/layout.tsx
  app/myhistory/mock.ts
  app/myhistory/page.tsx
  app/page.tsx
  components/header/header.tsx
  lib/apis/type/index.ts
  lib/apis/user/index.ts
  utils/convert-date.ts
Labels: ✨ feat

#86 feat: tanstack query 세팅
  app/layout.tsx
  app/providers.tsx
  package.json
  pnpm-lock.yaml
Labels: ✨ feat

#89 refactor: ButtonFloating 컴포넌트 onClick prop 추가
  components/button-floating/button-floating.tsx
Labels: ♻️ refactor

#92 feat: 비밀번호 재설정 기능 구현
  app/(auth)/login/_components/login-form.tsx
  app/(auth)/reset-password/_components/modal-send-email.tsx
  app/(auth)/reset-password/_components/reset-password-form.tsx
  app/(auth)/reset-password/page.tsx
  app/page.tsx
  components/header/logged-in-header.tsx
  components/modal/modal.tsx
  lib/apis/auth/index.ts
  lib/apis/user/index.ts
  middleware.ts
  schemas/auth.ts
Labels: ✨ feat

#91 feat: 팀 페이지 반응형 구현
  app/[groupId]/_components/member-list.tsx
  app/[groupId]/_components/task-lists.tsx
  app/[groupId]/_components/team.tsx
  app/[groupId]/edit/layout.tsx
  app/[groupId]/edit/page.tsx
  app/[groupId]/layout.tsx
  app/[groupId]/page.tsx
  app/[groupId]/tasks/_components/calendar-button.tsx
  app/[groupId]/tasks/_components/check-button.tsx
  app/[groupId]/tasks/_components/noTodo.tsx
  app/[groupId]/tasks/_components/todo-box-Container.tsx
  app/[groupId]/tasks/_components/todo-box.tsx
  app/[groupId]/tasks/_components/todo-contents.tsx
  app/[groupId]/tasks/_components/todo-contianer.tsx
  app/[groupId]/tasks/_components/todo-header.tsx
  app/[groupId]/tasks/_components/todo-list-name.tsx
  app/[groupId]/tasks/_hooks/use-calendar.ts
  app/[groupId]/tasks/layout.tsx
  app/[groupId]/tasks/page.tsx
  app/[teamId]/_components/members.tsx
  app/[teamId]/action.ts
  components/popover/popover.tsx
  lib/apis/group/index.ts
  public/icons/default-profile.svg
  tailwind.config.ts
Labels: ✨ feat

#96 feat: 모바일 사이드바 구현
  components/header/group-dropdown.tsx
  components/header/logged-in-header.tsx
  components/header/modal-side-menu.tsx
  components/header/side-menu.tsx
Labels: ✨ feat

#100 feat: 팝오버에 클릭이벤트 추가
  app/[groupId]/_components/team.tsx
  app/[groupId]/tasks/_components/comment.tsx
  components/header/popover-trigger.tsx
  components/popover/popover.tsx
Labels: ✨ feat

#104 refactor: myFetch 함수 구현
  app/(auth)/login/_components/login-form.tsx
  app/action.ts
  components/header/header.tsx
  lib/apis/auth/index.ts
  lib/apis/myFetch/clientFetch.ts
  lib/apis/myFetch/index.ts
  lib/apis/myFetch/serverFetch.ts
  lib/apis/user/index.ts
  middleware.ts
  next.config.mjs
Labels: ♻️ refactor

#106 fix: zustand store 불변 객체 관련 로직 수정
  providers/modal-store-provider.tsx
  stores/modal-store.ts
Labels: 🐛 fix

#97 feat: 리포트 컴포넌트 구현
  app/[groupId]/_components/member-list.tsx
  app/[groupId]/_components/task-report.tsx
  app/[groupId]/_components/team.tsx
  app/[groupId]/_components/today-task-progress-chart.tsx
  app/[groupId]/_components/today-task-progress.tsx
  app/[groupId]/_components/today-task-summary.tsx
  app/[groupId]/layout.tsx
  app/[groupId]/page.tsx
  package.json
  pnpm-lock.yaml
  public/images/done.png
  public/images/todo.png
Labels: ✨ feat

#107 refactor: 마이 히스토리 페이지 api 연결
  app/loading.tsx
  app/myhistory/_components/date-box-card.tsx
  app/myhistory/_components/date-box-list.tsx
  app/myhistory/mock.ts
  app/myhistory/page.tsx
  app/not-found.tsx
  lib/apis/type/index.ts
  utils/convert-date.ts
Labels: ♻️ refactor

#109 feat: 로그아웃 구현
  components/header/components/modal-logout.tsx
  components/header/popover-trigger.tsx
Labels: ✨ feat

#111 feat: 팀 수정하기, 삭제하기 모달 연결
  app/[groupId]/_components/modal-team-delete.tsx
  app/[groupId]/_components/modal-team-name-edit.tsx
  app/[groupId]/_components/team-name.tsx
  app/[groupId]/_components/today-task-progress.tsx
  app/[groupId]/page.tsx
  app/[teamId]/_components/members.tsx
Labels: ✨ feat

#108 fix: 리액트 쿼리 디하이드레이션 작업
  app/[groupId]/page.tsx
  app/[groupId]/tasks/_components/no-items/no-list.tsx
  app/[groupId]/tasks/_components/no-items/no-todo.tsx
  app/[groupId]/tasks/_components/side-bar.tsx
  app/[groupId]/tasks/_components/todo-box-Container.tsx
  app/[groupId]/tasks/_components/todo-contents.tsx
  app/[groupId]/tasks/_components/todo-contianer.tsx
  app/[groupId]/tasks/_components/todo/todo-box.tsx
  app/[groupId]/tasks/_components/todo/todo-contents.tsx
  app/[groupId]/tasks/_components/todo/todo-contianer.tsx
  app/[groupId]/tasks/_components/todo/todo-header.tsx
  app/[groupId]/tasks/_components/todo/todo-list-name.tsx
  app/[groupId]/tasks/_hooks/use-select-button.ts
  app/[groupId]/tasks/_hooks/use-side-bar.ts
  app/[groupId]/tasks/page.tsx
  lib/apis/group/index.ts
  lib/apis/task-list/index.ts
  lib/apis/task-list/type/index.ts
  lib/apis/task/hooks/use-get-task.ts
  lib/apis/task/hooks/use-get-tasks.ts
  lib/apis/task/index.ts
  lib/apis/task/type/index.ts
  lib/apis/user/index.ts
  pnpm-lock.yaml
  utils/convert-date.ts
Labels: ✨ feat

#115 fix: convertDateToYM 리턴값에 맞게 태그에 적용
  app/[groupId]/tasks/_components/todo/todo-box.tsx
Labels: 🐛 fix

#122 feat: 목록, 멤버 모달 연결
  app/[groupId]/_components/member-list.tsx
  app/[groupId]/_components/modal-team-delete.tsx
  app/[groupId]/_components/modal/modal-member-invitation.tsx
  app/[groupId]/_components/modal/modal-member-profile.tsx
  app/[groupId]/_components/modal/modal-task-list-add.tsx
  app/[groupId]/_components/modal/modal-task-list-delete.tsx
  app/[groupId]/_components/modal/modal-task-list-name-edit.tsx
  app/[groupId]/_components/modal/modal-team-delete.tsx
  app/[groupId]/_components/modal/modal-team-name-edit.tsx
  app/[groupId]/_components/task-lists.tsx
  app/[groupId]/_components/team-name.tsx
  app/[groupId]/page.tsx
  components/popover/popover.tsx
  lib/apis/group/index.ts
  lib/apis/type/index.ts
  pnpm-lock.yaml
Labels: ✨ feat

#118 feat: 자유 게시판 페이지 ui 구현
  app/(free-board)/_components/add-board-modal.tsx
  app/(free-board)/_components/add-board.tsx
  app/(free-board)/_components/card.tsx
  app/(free-board)/addboard/layout.tsx
  app/(free-board)/addboard/page.tsx
  app/(free-board)/boards/_components/ordered-by-selector.tsx
  app/(free-board)/boards/_components/post-list.tsx
  app/(free-board)/boards/_components/ranking-chart.tsx
  app/(free-board)/boards/_components/search-bar.tsx
  app/(free-board)/boards/_components/tag-list.tsx
  app/(free-board)/boards/mock.ts
  app/(free-board)/boards/page.tsx
  app/(free-board)/layout.tsx
  app/(free-board)/not-found.tsx
  app/action.ts
  app/layout.tsx
  app/myhistory/layout.tsx
  app/myhistory/page.tsx
  components/dropdown/dropdown.tsx
  components/header/logged-in-header.tsx
  components/input-field/basic-input.tsx
  constants/search-tags.ts
  lib/apis/article/index.ts
  lib/apis/type/index.ts
  lib/apis/user/index.ts
  next.config.mjs
  package.json
  pnpm-lock.yaml
  postcss.config.mjs
  public/icons/fire.svg
  public/icons/heart.svg
  public/icons/like-button.svg
  public/icons/medal.svg
  public/icons/search.svg
Labels: ✨ feat

#112 feat: 소셜 로그인 구현
  .gitignore
  app/(auth)/_components/easy-auth.tsx
  app/(auth)/_components/easy-login-button.tsx
  app/(auth)/login/_components/login-form.tsx
  app/(auth)/oauth/_components/auth-redirect.tsx
  app/(auth)/oauth/google/page.tsx
  app/(auth)/oauth/kakao/page.tsx
  app/(auth)/reset-password/_components/modal-send-email.tsx
  app/(auth)/reset-password/_components/reset-password-form.tsx
  app/(auth)/signup/_components/signup-form.tsx
  app/(auth)/signup/page.tsx
  constants/oauth.ts
  lib/apis/auth/index.ts
  lib/apis/type/index.ts
  lib/apis/user/index.ts
  middleware.ts
Labels: ✨ feat

#128 feat: todoBox 반복여부 제외하고 구현 완료 댓글 가져오기 기능 구현 완료
  app/[groupId]/tasks/_components/check-box.tsx
  app/[groupId]/tasks/_components/comment.tsx
  app/[groupId]/tasks/_components/side-bar.tsx
  app/[groupId]/tasks/_components/todo/todo-box.tsx
  app/[groupId]/tasks/_components/todo/todo-contents.tsx
  app/[groupId]/tasks/_hooks/use-side-bar.ts
  components/profile-Icon/profile-icon.tsx
  lib/apis/task/hooks/use-get-task.ts
  utils/checkTodo.ts
  utils/convert-date.ts
Labels: ✨ feat

#131 feat: 자유게시판 상품 등록 모달 구현
  app/(free-board)/_components/add-board-modal.tsx
  app/(free-board)/_components/add-board-modal/_components/file-drag-down.tsx
  app/(free-board)/_components/add-board-modal/_components/modal-cancel.tsx
  app/(free-board)/_components/add-board-modal/index.tsx
  app/(free-board)/_components/add-board-modal/schema/index.ts
  app/(free-board)/_components/add-board.tsx
  app/(free-board)/_components/card.tsx
  app/(free-board)/boards/_components/ordered-by-selector.tsx
  app/(free-board)/boards/page.tsx
  components/input-field/textarea.tsx
  components/modal/modal.tsx
  hooks/use-prevent-scroll.ts
  utils/scroll.ts
Labels: ✨ feat

#130 refactor: 리포트 반응형 수정
  app/[groupId]/_components/today-task-progress-chart.tsx
  app/[groupId]/_components/today-task-progress.tsx
  package.json
  pnpm-lock.yaml
Labels: ♻️ refactor

#135 feat: 자유게시판 상세 페이지 ui 구현
  app/(free-board)/_components/card.tsx
  app/(free-board)/board/[boardId]/layout.tsx
  app/(free-board)/board/[boardId]/page.tsx
  app/(free-board)/boards/[boardId]/_components/comments-list/_components/comment-card.tsx
  app/(free-board)/boards/[boardId]/_components/comments-list/index.tsx
  app/(free-board)/boards/[boardId]/_components/like-section.tsx
  app/(free-board)/boards/[boardId]/_components/post-comment.tsx
  app/(free-board)/boards/[boardId]/_components/post-kebab-button.tsx
  app/(free-board)/boards/[boardId]/layout.tsx
  app/(free-board)/boards/[boardId]/page.tsx
  app/(free-board)/boards/_components/post-list.tsx
  app/(free-board)/boards/_components/ranking-chart.tsx
  app/(free-board)/boards/error.tsx
  app/(free-board)/boards/mock.ts
  app/(free-board)/not-found.tsx
  app/global-error.tsx
Labels: ✨ feat

#142 chore: 카카오 계정 이미지 도메인 추가
  next.config.mjs
Labels: 📦 chore

#137 refactor: 프로필 인풋 컴포넌트 리팩토링
  app/mypage/_component/update-user-form.tsx
  app/mypage/layout.tsx
  app/mypage/page.tsx
  components/header/popover-trigger.tsx
  components/input-field/basic-input.tsx
  components/input-field/password-input.tsx
  components/profile-input/profile-input.tsx
  lib/apis/user/index.ts
  schemas/user.ts
Labels: ♻️ refactor

#144 refactor: 텐스택 쿼리로 리팩토링 및 로딩 설정
  app/(auth)/_hooks/use-auth-error.ts
  app/(auth)/login/_components/login-form.tsx
  app/(auth)/oauth/_components/auth-redirect.tsx
  app/(auth)/reset-password/_components/modal-send-email.tsx
  app/(auth)/reset-password/_components/reset-password-form.tsx
  app/(auth)/signup/_components/signup-form.tsx
  app/mypage/_component/modal-reset-password.tsx
  app/mypage/_component/modal-secession.tsx
  app/mypage/_component/secession- button.tsx
  app/mypage/_component/update-user-form.tsx
  app/mypage/page.tsx
  components/header/LoggedIn-header-content.tsx
  components/header/components/modal-logout.tsx
  components/header/logged-in-header.tsx
  components/input-field/basic-input.tsx
  components/input-field/password-input.tsx
  components/profile-input/profile-input.tsx
  public/icons/exit-door.svg
  schemas/user.ts
Labels: ♻️ refactor

#134 feat: 팀 명 수정하기, 팀 삭제하기 기능 구현
  app/[groupId]/_components/modal/modal-member-invitation.tsx
  app/[groupId]/_components/modal/modal-team-delete.tsx
  app/[groupId]/_components/modal/modal-team-name-edit.tsx
  app/[groupId]/_components/team-name.tsx
  app/[groupId]/page.tsx
  lib/apis/group/index.ts
  lib/apis/myFetch/index.ts
Labels: ✨ feat

#149 refactor: myFetch 인스턴스 기능 추가
  lib/apis/myFetch/index.ts
  lib/apis/myFetch/instance.ts
Labels: ♻️ refactor

#143 feat: 댓글 등록기능 및 done 기능 토글
  app/[groupId]/tasks/_components/check-box.tsx
  app/[groupId]/tasks/_components/check-button.tsx
  app/[groupId]/tasks/_components/comment-input.tsx
  app/[groupId]/tasks/_components/side-bar.tsx
  app/[groupId]/tasks/_components/todo/todo-box.tsx
  app/[groupId]/tasks/_components/todo/todo-contents.tsx
  app/[groupId]/tasks/_components/todo/todo-header.tsx
  app/[groupId]/tasks/_hooks/use-side-bar.ts
  lib/apis/comment/index.ts
  lib/apis/comment/type/index.ts
  lib/apis/task/hooks/use-get-task.ts
  lib/apis/task/hooks/use-path-task.ts
  lib/apis/task/index.ts
  lib/apis/task/type/index.ts
  utils/checkTodo.ts
Labels: ✨ feat

#150 fix: 백엔드 인터페이스 변경에 따른 myhistory 로직 변경
  app/myhistory/_components/date-box-card.tsx
  app/myhistory/_components/date-box-list.tsx
  lib/apis/type/index.ts
  lib/apis/user/index.ts
Labels: 🐛 fix

#153 fix: 백엔드 인터페이스 변경에 따른 리스트 페이지 로직 변경
  app/[groupId]/tasks/_components/comment-input.tsx
  app/[groupId]/tasks/_components/side-bar.tsx
  app/[groupId]/tasks/page.tsx
  lib/apis/comment/index.ts
  lib/apis/comment/type/index.ts
  lib/apis/recurring/index.ts
  lib/apis/task-list/index.ts
  lib/apis/task-list/type/index.ts
  lib/apis/task/hooks/use-get-tasks.ts
  lib/apis/task/hooks/use-path-task.ts
  lib/apis/task/index.ts
  lib/apis/task/type/index.ts
  utils/checkTodo.ts
  utils/convert-date.ts
Labels: 🐛 fix

#145 feat: 팀 참여하기 페이지 구현
  app/(team-setting)/participate-team/_components/participate-team-form.tsx
  app/(team-setting)/participate-team/page.tsx
  app/[groupId]/_components/modal/modal-member-invitation.tsx
  components/header/popover-trigger.tsx
  lib/apis/group/index.ts
Labels: ✨ feat

#159 feat: 팀 페이지 관리자용, 멤버용 분리
  app/[groupId]/_components/member-list.tsx
  app/[groupId]/_components/task-lists.tsx
  app/[groupId]/_components/team-name.tsx
  app/[groupId]/page.tsx
Labels: ✨ feat

#156 fix: 드롭다운 새로고침 버그 해결
  app/(free-board)/boards/_components/ordered-by-selector.tsx
  components/button/variants/index.ts
  components/dropdown/dropdown.tsx
  components/header/group-dropdown.tsx
  components/header/modal-side-menu.tsx
Labels: 🐛 fix

#164 feat: 멤버 삭제 기능 구현
  app/[groupId]/_components/member-list.tsx
  app/[groupId]/_components/modal/modal-member-delete.tsx
  lib/apis/group/index.ts
  lib/apis/type/index.ts
Labels: ✨ feat

#160 feat: 자유게시판 페이지 텐스택 쿼리 추가
  app/(free-board)/_components/add-board-modal/_components/file-drag-down.tsx
  app/(free-board)/_components/add-board.tsx
  app/(free-board)/_components/article-modal/_components/file-drag-down.tsx
  app/(free-board)/_components/article-modal/_components/modal-cancel.tsx
  app/(free-board)/_components/article-modal/edit-article-modal.tsx
  app/(free-board)/_components/article-modal/index.tsx
  app/(free-board)/_components/article-modal/schema/index.ts
  app/(free-board)/_query/query.ts
  app/(free-board)/boards/_components/ordered-by-selector.tsx
  app/(free-board)/boards/_components/post-header.tsx
  app/(free-board)/boards/_components/post-list.tsx
  app/(free-board)/boards/_components/ranking-chart.tsx
  app/(free-board)/boards/_components/reset-button.tsx
  app/(free-board)/boards/_components/search-bar.tsx
  app/(free-board)/boards/_components/skeleton-components/skeleton-ranking-chart.tsx
  app/(free-board)/boards/_components/tag-list.tsx
  app/(free-board)/boards/page.tsx
  app/(free-board)/error.tsx
  app/(free-board)/layout.tsx
  app/(free-board)/loading.tsx
  app/layout.tsx
  app/loading.tsx
  components/button/button.tsx
  components/pagination/pagination.tsx
  components/pagination/skeleton/skeleton-pagination.tsx
  lib/apis/article-comment/index.ts
  lib/apis/article/index.ts
  lib/show-toast/index.tsx
  providers/sort-store-provider.tsx
  public/icons/arrow-first.svg
  public/icons/arrow-last.svg
  public/icons/arrow-return.tsx
  stores/sort-store.ts
Labels: ✨ feat

#169 feat: 팀 페이지 탠스택 쿼리 적용, 에러 메세지 변경
  app/[groupId]/_components/member-list.tsx
  app/[groupId]/_components/modal/modal-member-delete.tsx
  app/[groupId]/_components/modal/modal-member-invitation.tsx
  app/[groupId]/_components/modal/modal-task-list-add.tsx
  app/[groupId]/_components/modal/modal-task-list-delete.tsx
  app/[groupId]/_components/modal/modal-task-list-name-edit.tsx
  app/[groupId]/_components/modal/modal-team-delete.tsx
  app/[groupId]/_components/modal/modal-team-name-edit.tsx
  app/[groupId]/_components/task-lists.tsx
  app/[groupId]/_components/task-report.tsx
  app/[groupId]/_components/team-name.tsx
  app/[groupId]/page.tsx
  lib/apis/group/index.ts
  lib/apis/task-list/index.ts
Labels: ✨ feat

#172 refactor: 로딩 토스트 추가 및 instansce로 변경, 불필요한 async await 삭제
  app/(auth)/login/_components/login-form.tsx
  app/(auth)/oauth/_components/auth-redirect.tsx
  app/(auth)/reset-password/_components/modal-send-email.tsx
  app/(auth)/reset-password/_components/reset-password-form.tsx
  app/(auth)/signup/_components/signup-form.tsx
  app/mypage/_component/modal-reset-password.tsx
  app/mypage/_component/modal-secession.tsx
  app/mypage/_component/update-user-form.tsx
  lib/apis/auth/index.ts
  lib/apis/image/index.ts
  lib/apis/user/index.ts
Labels: ♻️ refactor

#171 refactor: 자유게시판 메인 페이지 리팩토링
  app/(free-board)/_components/add-article.tsx
  app/(free-board)/_components/article-modal/edit-article-modal.tsx
  app/(free-board)/_components/article-modal/index.tsx
  app/(free-board)/_query/mutation.ts
  app/(free-board)/_query/query.ts
  app/(free-board)/boards/[boardId]/_components/comment-card.tsx
  app/(free-board)/boards/[boardId]/_components/comments-list.tsx
  app/(free-board)/boards/_components/article-header.tsx
  app/(free-board)/boards/_components/article-list/article-card.tsx
  app/(free-board)/boards/_components/article-list/articles-list.tsx
  app/(free-board)/boards/_components/article-list/no-article.tsx
  app/(free-board)/boards/_components/article-orderby-dropdown.tsx
  app/(free-board)/boards/_components/article-ranking-chart.tsx
  app/(free-board)/boards/_components/article-reset-button.tsx
  app/(free-board)/boards/_components/article-search-bar.tsx
  app/(free-board)/boards/_components/article-tag-list.tsx
  app/(free-board)/boards/_components/ordered-by-selector.tsx
  app/(free-board)/boards/_components/pagination/pagination-indicator.tsx
  app/(free-board)/boards/_components/pagination/pagination.tsx
  app/(free-board)/boards/_components/post-header.tsx
  app/(free-board)/boards/_components/post-list.tsx
  app/(free-board)/boards/_components/ranking-chart.tsx
  app/(free-board)/boards/_components/reset-button.tsx
  app/(free-board)/boards/_components/search-bar.tsx
  app/(free-board)/boards/_components/skeleton-components/skeleton-article-list.tsx
  app/(free-board)/boards/_components/skeleton-components/skeleton-article-pagination.tsx
  app/(free-board)/boards/_components/skeleton-components/skeleton-ranking-chart.tsx
  app/(free-board)/boards/page.tsx
  app/(free-board)/layout.tsx
  app/layout.tsx
  components/dropdown/dropdown.tsx
  components/pagination/pagination.tsx
  lib/apis/article/index.ts
  providers/sort-store-provider.tsx
  stores/modal-store.ts
  stores/sort-store.ts
Labels: ♻️ refactor

#178 fix: 드롭다운 관련 버그 해결 및 더보기, 숨기기 버튼 추가
  components/dropdown/dropdown.tsx
  components/header/group-dropdown.tsx
Labels: 🐛 fix

#180 feat: 소셜 로그인 로딩 UI 수정
  app/(auth)/oauth/_components/auth-redirect.tsx
  app/(auth)/oauth/google/page.tsx
  app/(auth)/oauth/kakao/page.tsx
  package.json
  pnpm-lock.yaml
  public/lotties/loading-earthworm.json
  public/lotties/spinner.json
Labels: ✨ feat, 💄design

#187 feat: progress bar 구현
  app/(free-board)/_components/add-article.tsx
  app/(free-board)/boards/_components/article-list/article-card.tsx
  app/(free-board)/boards/_components/article-orderby-dropdown.tsx
  app/(free-board)/boards/_components/article-ranking-chart.tsx
  app/(free-board)/boards/_components/article-search-bar.tsx
  app/(free-board)/boards/_components/article-tag-list.tsx
  app/(free-board)/boards/_components/pagination/pagination.tsx
  app/(free-board)/boards/page.tsx
  app/layout.tsx
  components/button/button.tsx
  components/header/LoggedIn-header-content.tsx
  components/link-with-progress/index.tsx
  hooks/use-progress.ts
  package.json
  pnpm-lock.yaml
  providers/progress-bar-provider.tsx
  styles/globals.css
  utils/shorten-string.ts
Labels: ✨ feat

#181 feat: 할 일 목록 드래그앤드롭으로 순서 변경하는 기능 구현
  app/[groupId]/_components/strict-mode-droppable.tsx
  app/[groupId]/_components/task-lists.tsx
  lib/apis/task-list/index.ts
  package.json
  pnpm-lock.yaml
Labels: ✨ feat

#191 refactor: 자유게시판 목록 페이지 UI 개선
  app/(free-board)/_components/card.tsx
  app/(free-board)/boards/_components/article-header.tsx
  app/(free-board)/boards/_components/article-list/articles-list.tsx
  app/(free-board)/boards/_components/article-list/no-article.tsx
  app/(free-board)/boards/_components/article-orderby-dropdown.tsx
  app/(free-board)/boards/_components/pagination/pagination.tsx
  app/(free-board)/boards/page.tsx
  app/(free-board)/layout.tsx
Labels: ♻️ refactor

#183 feat: 할일 추가기능 구현 및 사이드바에 할일 완료 구현
  app/[groupId]/tasks/_components/modal/add-List-modal.tsx
  app/[groupId]/tasks/_components/modal/add-todo-modal/day-button.tsx
  app/[groupId]/tasks/_components/modal/add-todo-modal/frequency-dropdown.tsx
  app/[groupId]/tasks/_components/modal/add-todo-modal/index.tsx
  app/[groupId]/tasks/_components/modal/add-todo-modal/todo-calendar-button.tsx
  app/[groupId]/tasks/_components/modal/delete-todo-modal.tsx
  app/[groupId]/tasks/_components/no-items/no-list.tsx
  app/[groupId]/tasks/_components/no-items/no-todo.tsx
  app/[groupId]/tasks/_components/side-bar.tsx
  app/[groupId]/tasks/_components/todo/kebab-popover.tsx
  app/[groupId]/tasks/_components/todo/todo-box.tsx
  app/[groupId]/tasks/_components/todo/todo-contents.tsx
  app/[groupId]/tasks/_components/todo/todo-contianer.tsx
  app/[groupId]/tasks/_hooks/use-select-button.ts
  app/[groupId]/tasks/page.tsx
  components/popover/popover.tsx
  lib/apis/recurring/index.ts
  lib/apis/task/hooks/use-path-task.ts
  lib/apis/task/hooks/use-post-task.ts
  lib/apis/task/index.ts
  lib/apis/task/type/index.ts
  public/icons/alert.svg
  schemas/task.ts
  tsconfig.json
Labels: ✨ feat

#195 feat: no-team 페이지 구현
  app/no-team/page.tsx
  public/images/no-team.png
Labels: ✨ feat

#200 fix: todoBox sideBar에 frequncy 나오도록 출력
  app/[groupId]/tasks/_components/modal/add-todo-modal/frequency-dropdown.tsx
  app/[groupId]/tasks/_components/modal/add-todo-modal/index.tsx
  app/[groupId]/tasks/_components/modal/add-todo-modal/todo-calendar-button.tsx
  app/[groupId]/tasks/_components/modal/delete-todo-modal.tsx
  app/[groupId]/tasks/_components/side-bar.tsx
  app/[groupId]/tasks/_components/todo/todo-box.tsx
  app/[groupId]/tasks/_components/todo/todo-contents.tsx
  utils/convert-frequency.ts
Labels: 🐛 fix

#192 feat: 팀 생성하기 페이지 구현
  app/(team-setting)/addteam/_component/add-team-form.tsx
  app/(team-setting)/addteam/page.tsx
  components/profile-input/profile-input.tsx
  lib/apis/group/index.ts
  public/icons/image.svg
  schemas/team.ts
Labels: ✨ feat

#194 feat: 자유게시판 상세 페이지 텐스택 쿼리 추가
  app/(free-board)/_components/add-article.tsx
  app/(free-board)/_components/article-modal/_components/file-drag-down.tsx
  app/(free-board)/_components/article-modal/edit-article-modal.tsx
  app/(free-board)/_components/article-modal/index.tsx
  app/(free-board)/_components/card.tsx
  app/(free-board)/_components/handle-article-modal/article-form.tsx
  app/(free-board)/_components/handle-article-modal/file-drag-down.tsx
  app/(free-board)/_components/handle-article-modal/index.tsx
  app/(free-board)/_components/handle-article-modal/schema/index.ts
  app/(free-board)/_components/modal-cancel.tsx
  app/(free-board)/_components/modal-delete.tsx
  app/(free-board)/_components/modal-error.tsx
  app/(free-board)/_components/upload-article-button.tsx
  app/(free-board)/_query/mutation.ts
  app/(free-board)/_query/query.ts
  app/(free-board)/boards/[boardId]/_components/article-kebab-button.tsx
  app/(free-board)/boards/[boardId]/_components/comment-card.tsx
  app/(free-board)/boards/[boardId]/_components/comment-edit-card.tsx
  app/(free-board)/boards/[boardId]/_components/comment-form.tsx
  app/(free-board)/boards/[boardId]/_components/comments-list.tsx
  app/(free-board)/boards/[boardId]/_components/like-section.tsx
  app/(free-board)/boards/[boardId]/_components/post-comment.tsx
  app/(free-board)/boards/[boardId]/_components/post-kebab-button.tsx
  app/(free-board)/boards/[boardId]/page.tsx
  app/(free-board)/boards/_components/article-list/article-card.tsx
  app/(free-board)/boards/_components/article-list/articles-list.tsx
  app/(free-board)/boards/_components/pagination/pagination.tsx
  app/(free-board)/boards/_components/skeleton-components/skeleton-article-list.tsx
  app/(free-board)/boards/_components/skeleton-components/skeleton-article-pagination.tsx
  app/(free-board)/boards/_components/skeleton-components/skeleton-card-list.tsx
  app/(free-board)/boards/page.tsx
  app/(free-board)/layout.tsx
  components/intersection-area/intersection-area.tsx
  hooks/use-next-page.ts
  lib/apis/article-comment/index.ts
  lib/apis/article/index.ts
  lib/apis/type/index.ts
  public/icons/kebab-hover.tsx
  public/icons/kebab-large.tsx
  public/icons/like-button-colored.tsx
  public/icons/like-button.svg
  public/icons/media-icon.svg
  public/icons/tube-spinner.svg
Labels: ✨ feat

#190 refactor: 랜딩 애니메이션 적용 및 Link 연결
  app/page.tsx
  components/header/modal-side-menu.tsx
  components/landing/Logged-in-button-content.tsx
  components/landing/landing-card.tsx
  components/landing/landing-first-card.tsx
  components/landing/landing-header.tsx
  components/landing/logged-in-button.tsx
  tailwind.config.ts
Labels: ♻️ refactor

#202 fix: progress bar 전체 적용
  app/(auth)/login/_components/login-form.tsx
  app/(auth)/oauth/_components/auth-redirect.tsx
  app/(auth)/reset-password/_components/reset-password-form.tsx
  app/(auth)/signup/_components/signup-form.tsx
  app/(free-board)/boards/_components/article-orderby-dropdown.tsx
  app/(free-board)/boards/_components/article-ranking-chart.tsx
  app/(free-board)/boards/_components/article-tag-list.tsx
  app/(team-setting)/addteam/_component/add-team-form.tsx
  app/[groupId]/_components/modal/modal-member-delete.tsx
  app/[groupId]/_components/modal/modal-task-list-add.tsx
  app/[groupId]/_components/modal/modal-task-list-delete.tsx
  app/[groupId]/_components/modal/modal-task-list-name-edit.tsx
  app/[groupId]/_components/modal/modal-team-delete.tsx
  app/[groupId]/_components/modal/modal-team-name-edit.tsx
  app/mypage/_component/modal-secession.tsx
  components/header/LoggedIn-header-content.tsx
  components/header/components/modal-logout.tsx
  components/header/group-dropdown.tsx
  components/header/modal-side-menu.tsx
  components/header/popover-trigger.tsx
  components/link-with-progress/index.tsx
  hooks/use-progress.ts
Labels: 🐛 fix

#203 refactor: 버튼 disabled 풀리는 문제 해결
  app/(auth)/login/_components/login-form.tsx
  app/mypage/_component/update-user-form.tsx
Labels: ♻️ refactor

#215 feat: 라이트 모드 구현
  app/(auth)/_components/easy-auth.tsx
  app/(free-board)/error.tsx
  app/[groupId]/_components/member-list.tsx
  app/[groupId]/_components/task-lists.tsx
  app/[groupId]/_components/team-name.tsx
  app/[groupId]/tasks/_components/todo/todo-header.tsx
  app/global-error.tsx
  app/globals.css
  app/layout.tsx
  components/button/variants/index.ts
  components/header/LoggedIn-header-content.tsx
  components/header/group-dropdown.tsx
  components/header/none-login-header.tsx
  components/header/popover-trigger.tsx
  components/landing/landing-card.tsx
  components/landing/landing-first-card.tsx
  components/theme/theme-provider.tsx
  components/theme/theme-toggle.tsx
  package.json
  pnpm-lock.yaml
  public/icons/dropdown-check.svg
  public/icons/moon.svg
  public/icons/plus.svg
  public/icons/search.svg
  public/icons/sun.svg
  public/icons/user.svg
  tailwind.config.ts
Labels: ✨ feat

#216 refactor: 팀 페이지 낙관적 업데이트 적용
  app/[groupId]/_components/modal/modal-member-delete.tsx
  app/[groupId]/_components/modal/modal-task-list-add.tsx
  app/[groupId]/_components/modal/modal-task-list-delete.tsx
  app/[groupId]/_components/modal/modal-task-list-name-edit.tsx
  app/[groupId]/_components/task-lists.tsx
Labels: ♻️ refactor

#206 feat: 팀 수정하기 페이지 구현
  app/[groupId]/_components/task-lists.tsx
  app/[groupId]/_components/team-name.tsx
  app/[groupId]/edit/_components/edit-team-form.tsx
  app/[groupId]/edit/page.tsx
  app/[groupId]/page.tsx
  lib/apis/group/index.ts
  schemas/team.ts
Labels: ✨ feat

#210 feat: 댓글 삭제 및 수정
  app/[groupId]/tasks/_components/comment.tsx
  app/[groupId]/tasks/_components/comment/comment-input.tsx
  app/[groupId]/tasks/_components/comment/comment.tsx
  app/[groupId]/tasks/_components/comment/kebab-pop-over.tsx
  app/[groupId]/tasks/_components/modal/add-todo-modal/index.tsx
  app/[groupId]/tasks/_components/side-bar.tsx
  app/[groupId]/tasks/_hooks/use-edit-comment.ts
  lib/apis/comment/hooks/use-delete-comment.ts
  lib/apis/comment/hooks/use-patch-comment.ts
Labels: ✨ feat

#213 feat: task 수정모달 만들기
  app/[groupId]/tasks/_components/check-box.tsx
  app/[groupId]/tasks/_components/comment/kebab-pop-over.tsx
  app/[groupId]/tasks/_components/modal/add-todo-modal/index.tsx
  app/[groupId]/tasks/_components/modal/day-button.tsx
  app/[groupId]/tasks/_components/modal/delete-todo-modal.tsx
  app/[groupId]/tasks/_components/modal/edit-todo-modal/index.tsx
  app/[groupId]/tasks/_components/modal/frequency-dropdown.tsx
  app/[groupId]/tasks/_components/modal/todo-calendar-button.tsx
  app/[groupId]/tasks/_components/side-bar.tsx
  app/[groupId]/tasks/_components/todo/kebab-popover.tsx
  app/[groupId]/tasks/_components/todo/todo-box.tsx
  app/[groupId]/tasks/_components/todo/todo-contents.tsx
  lib/apis/task/hooks/use-edit-task.ts
  lib/apis/task/hooks/use-toggle-done-task.ts
Labels: ✨ feat

#222 feat: loading.tsx 스피너 추가, not-found 구현
  app/(auth)/oauth/_components/auth-redirect.tsx
  app/loading.tsx
  app/not-found.tsx
  components/animation/not-found-animation.tsx
  public/icons/tube-spinner.svg
  public/lotties/not-found.json
Labels: ✨ feat

#220 refactor: 팀 페이지 UX/UI 개선
  app/[groupId]/_components/member-list.tsx
  app/[groupId]/_components/modal/modal-member-delete.tsx
  app/[groupId]/_components/modal/modal-task-list-add.tsx
  app/[groupId]/_components/modal/modal-task-list-delete.tsx
  app/[groupId]/_components/modal/modal-task-list-name-edit.tsx
  app/[groupId]/_components/modal/modal-team-delete.tsx
  app/[groupId]/_components/modal/modal-team-name-edit.tsx
  app/[groupId]/_components/task-lists.tsx
  lib/apis/group/index.ts
  public/icons/crown.png
  utils/has-last-consonant-letter.ts
Labels: ♻️ refactor

#233 refactor: 라이트모드 팀 페이지 스타일 수정
  app/[groupId]/_components/member-list.tsx
  app/[groupId]/_components/task-lists.tsx
  app/[groupId]/_components/team-name.tsx
  app/[groupId]/_components/today-task-progress-chart.tsx
  app/[groupId]/edit/_components/edit-team-form.tsx
  app/globals.css
  public/icons/gear.svg
  public/icons/image.svg
  public/icons/my-profile.svg
  public/images/thumbnail-team.png
  public/images/thumbnail_team.svg
  tailwind.config.ts
Labels: ♻️ refactor, 💄design

#229 refactor: 팀 페이지 리팩토링
  app/[groupId]/_components/member-list.tsx
  app/[groupId]/_components/team-name.tsx
  app/[groupId]/edit/_components/edit-team-form.tsx
  app/[groupId]/page.tsx
  components/header/group-dropdown.tsx
  components/header/modal-side-menu.tsx
  components/profile-input/profile-input.tsx
Labels: ♻️ refactor

#232 fix: todo 삭제가 안되는 버그 수정
  app/[groupId]/tasks/_components/modal/delete-todo-modal.tsx
  app/[groupId]/tasks/_components/side-bar.tsx
  app/[groupId]/tasks/_components/todo/todo-box.tsx
  app/[groupId]/tasks/_components/todo/todo-contents.tsx
Labels: 🐛 fix

#230 refector: 달력UI 개선
  app/[groupId]/tasks/_components/calendar-style/custom-date-picker.css
  app/[groupId]/tasks/_components/modal/add-todo-modal/index.tsx
  app/[groupId]/tasks/_components/modal/todo-calendar-button.tsx
  app/[groupId]/tasks/_components/side-bar.tsx
  app/[groupId]/tasks/_components/todo/todo-header.tsx
  components/profile-Icon/profile-icon.tsx
Labels: ♻️ refactor, 💄design

#237 refactor: 자유게시판 UI, UX 개선 및 백엔드 데이터 구조 변경에 따른 개선
  app/(free-board)/_components/card.tsx
  app/(free-board)/_components/handle-article-modal/article-form.tsx
  app/(free-board)/_components/handle-article-modal/file-drag-down.tsx
  app/(free-board)/_components/upload-article-button.tsx
  app/(free-board)/_query/mutation.ts
  app/(free-board)/_query/query.ts
  app/(free-board)/boards/[boardId]/_components/article-header.tsx
  app/(free-board)/boards/[boardId]/_components/comment-card.tsx
  app/(free-board)/boards/[boardId]/_components/comment-form.tsx
  app/(free-board)/boards/[boardId]/_components/comments-list.tsx
  app/(free-board)/boards/[boardId]/_components/like-section.tsx
  app/(free-board)/boards/_components/article-list/article-card.tsx
  app/(free-board)/boards/_components/article-list/articles-list.tsx
  app/(free-board)/boards/_components/article-orderby-dropdown.tsx
  app/(free-board)/boards/_components/article-ranking-chart.tsx
  app/(free-board)/boards/_components/article-search-bar.tsx
  app/(free-board)/boards/_components/article-tag-list.tsx
  app/(free-board)/boards/page.tsx
  app/(free-board)/layout.tsx
  app/(free-board)/loading.tsx
  components/intersection-area/intersection-area.tsx
  lib/apis/type/index.ts
  providers/toast-provider.tsx
  public/icons/media-icon.svg
  public/icons/x.svg
Labels: ♻️ refactor

#234 refactor: 타입 TeamId 삭제 및 불필요한 주석 삭제
  app/(auth)/login/_components/login-form.tsx
  app/(auth)/reset-password/_components/modal-send-email.tsx
  app/[groupId]/_components/member-list.tsx
  app/[groupId]/_components/modal/modal-member-delete.tsx
  app/[groupId]/_components/modal/modal-task-list-add.tsx
  app/[groupId]/_components/modal/modal-task-list-delete.tsx
  app/[groupId]/_components/modal/modal-task-list-name-edit.tsx
  app/[groupId]/_components/task-lists.tsx
  app/[groupId]/tasks/_components/todo/todo-contents.tsx
  app/[groupId]/tasks/_hooks/use-select-button.ts
  app/myhistory/_components/date-box-card.tsx
  app/myhistory/_components/date-box-list.tsx
  components/header/LoggedIn-header-content.tsx
  components/header/group-dropdown.tsx
  components/header/modal-side-menu.tsx
  components/header/popover-trigger.tsx
  components/header/side-menu.tsx
  components/input-field/password-input.tsx
  components/popover/popover.tsx
  lib/apis/auth/index.ts
  lib/apis/group/index.ts
  lib/apis/image/index.ts
  lib/apis/myFetch/clientFetch.ts
  lib/apis/myFetch/serverFetch.ts
  lib/apis/task-list/index.ts
  lib/apis/type/index.ts
  lib/apis/user/index.ts
  public/images/default-profile.png
Labels: ♻️ refactor

#244 fix: UI 개선
  app/globals.css
  components/header/LoggedIn-header-content.tsx
  components/header/popover-trigger.tsx
  components/input-field/basic-input.tsx
  components/landing/footer.tsx
  components/landing/landing-header.tsx
  tailwind.config.ts
Labels: 🐛 fix

#246 refactor: 전체적인 UI 개선
  app/[groupId]/_components/member-list.tsx
  app/[groupId]/_components/task-lists.tsx
  public/icons/default-profile.svg
  public/icons/my-profile.svg
  tailwind.config.ts
Labels: ♻️ refactor, 💄design

#254 fix: default 이미지 적용이 안되는 문제
  components/profile-Icon/profile-icon.tsx
Labels: 🐛 fix

#252 fix: 라이트 모드 스타일링 적용
  app/[groupId]/tasks/_components/calendar-style/custom-date-picker.css
  app/[groupId]/tasks/_components/comment/kebab-pop-over.tsx
  app/[groupId]/tasks/_components/modal/add-todo-modal/index.tsx
  app/[groupId]/tasks/_components/modal/day-button.tsx
  app/[groupId]/tasks/_components/modal/edit-todo-modal/index.tsx
  app/[groupId]/tasks/_components/modal/frequency-dropdown.tsx
  app/[groupId]/tasks/_components/modal/todo-calendar-button.tsx
  app/[groupId]/tasks/_components/side-bar.tsx
  app/[groupId]/tasks/_components/todo/kebab-popover.tsx
  app/[groupId]/tasks/_components/todo/todo-header.tsx
  app/[groupId]/tasks/_components/todo/todo-list-name.tsx
  app/globals.css
  stories/Header.stories.ts
  tailwind.config.ts
Labels: 🐛 fix

#248 feat: 오늘의 꼼꼼이 차트 추가
  app/[groupId]/_components/task-report.tsx
  app/[groupId]/_components/team-name.tsx
  app/[groupId]/_components/today-kkomkkom-people.tsx
  app/[groupId]/_components/today-task-progress.tsx
  lib/apis/type/index.ts
  public/icons/star.png
  tailwind.config.ts
Labels: ✨ feat

#251 fix: 자유게시판 쿼리 관련 에러 수정
  app/(free-board)/_query/mutation.ts
  app/(free-board)/boards/page.tsx
Labels: 🐛 fix

#249 refactor: 메모이제이션을 통해 성능 최적화
  components/header/group-dropdown.tsx
  components/header/modal-side-menu.tsx
  components/input-field/password-input.tsx
  components/landing/landing-header.tsx
  components/profile-input/profile-input.tsx
  components/theme/theme-toggle.tsx
Labels: ♻️ refactor

#256 fix:목록 추가되지 않는 버그 수정
  app/[groupId]/tasks/_components/modal/add-List-modal.tsx
Labels: 🐛 fix

#258 refactor: 번들링 사이즈 관련 성능 개선
  .eslintrc.json
  app/(auth)/_components/easy-login-button.tsx
  app/(auth)/oauth/_components/auth-redirect.tsx
  app/(free-board)/_components/card.tsx
  app/(free-board)/_components/handle-article-modal/file-drag-down.tsx
  app/(free-board)/_components/handle-article-modal/index.tsx
  app/(free-board)/_components/handle-article-modal/type.d.ts
  app/(free-board)/_components/modal-cancel.tsx
  app/(free-board)/_components/modal-delete.tsx
  app/(free-board)/_components/upload-article-button.tsx
  app/(free-board)/boards/[boardId]/_components/article-header.tsx
  app/(free-board)/boards/[boardId]/_components/like-section.tsx
  app/(free-board)/boards/_components/article-list/articles-list.tsx
  app/(free-board)/boards/_components/article-orderby-dropdown.tsx
  app/(free-board)/boards/_components/article-ranking-chart.tsx
  app/(free-board)/boards/_components/article-reset-button.tsx
  app/(free-board)/boards/_components/article-search-bar.tsx
  app/(free-board)/boards/_components/pagination/pagination-indicator.tsx
  app/(free-board)/boards/_components/pagination/pagination.tsx
  app/(free-board)/boards/_components/skeleton-components/skeleton-card-list.tsx
  app/(free-board)/error.tsx
  app/(free-board)/layout.tsx
  app/[groupId]/_components/task-lists.tsx
  app/[groupId]/_components/today-task-progress-chart.tsx
  app/global-error.tsx
  app/loading.tsx
  app/mypage/_component/modal-secession.tsx
  app/mypage/_component/secession- button.tsx
  app/no-team/page.tsx
  app/not-found.tsx
  components/button/button.tsx
  components/button/link-button.tsx
  components/header/LoggedIn-header-content.tsx
  components/header/group-dropdown.tsx
  components/header/modal-side-menu.tsx
  components/input-field/password-input.tsx
  components/landing/Logged-in-button-content.tsx
  components/landing/footer.tsx
  components/landing/landing-card.tsx
  components/landing/landing-first-card.tsx
  components/landing/landing-header.tsx
  components/theme/theme-toggle.tsx
  middleware.ts
  next.config.mjs
  package.json
  pnpm-lock.yaml
  postcss.config.mjs
  public/icons/eye-on.svg
  public/images/hamster.jpg
  public/images/landing-footer-large.png
  public/images/landing-footer-large.webp
  public/images/landing-header-large.png
  public/images/landing-header-large.webp
Labels: ♻️ refactor

#262 fix: 팀명 설정 아이콘 안 눌리는 버그 수정
  app/[groupId]/_components/team-name.tsx
Labels: 🐛 fix

#263 fix: 로그아웃, 탈퇴 및 쿼리 무효화
  app/mypage/_component/modal-secession.tsx
  components/header/components/modal-logout.tsx
Labels: 🐛 fix

#266 refactor: SEO 향상
  app/robot.ts
Labels: ♻️ refactor

#268 fix: 기본 프로필 svg로 변경
  components/profile-Icon/profile-icon.tsx
Labels: 🐛 fix

#271 fix: css 수정 및 에러 토스트 적용
  app/(auth)/reset-password/_components/modal-send-email.tsx
  app/(auth)/reset-password/_components/reset-password-form.tsx
  app/globals.css
  app/layout.tsx
  app/mypage/_component/modal-reset-password.tsx
  app/mypage/_component/update-user-form.tsx
  components/header/modal-side-menu.tsx
  components/landing/landing-header.tsx
  components/theme/theme-toggle.tsx
  styles/globals.css
Labels: 🐛 fix

#272 refactor: 라이트 하우스 관련 성능 개선
  app/(free-board)/_components/card.tsx
  app/(free-board)/_components/handle-article-modal/file-drag-down.tsx
  app/(free-board)/boards/[boardId]/_components/comment-card.tsx
  app/(free-board)/boards/[boardId]/_components/comment-edit-card.tsx
  app/(free-board)/boards/[boardId]/page.tsx
  app/(free-board)/boards/_components/article-orderby-dropdown.tsx
  app/(free-board)/boards/_components/article-ranking-chart.tsx
  app/(free-board)/boards/_components/article-search-bar.tsx
  app/(free-board)/boards/_components/article-tag-list.tsx
  app/(free-board)/boards/_components/pagination/pagination-indicator.tsx
  app/(free-board)/boards/_components/pagination/pagination.tsx
  app/(free-board)/boards/_components/upload-article-button.tsx
  app/(free-board)/boards/page.tsx
  app/(free-board)/layout.tsx
  app/[groupId]/tasks/_components/check-box.tsx
  app/[groupId]/tasks/_components/tasks-button.tsx
  components/button/link-button.tsx
  components/header/LoggedIn-header-content.tsx
  components/header/none-login-header.tsx
  components/landing/landing-header.tsx
  components/popover/popover.tsx
  hooks/use-progress.ts
  providers/progress-bar-provider.tsx
Labels: ♻️ refactor

#274 refactor: 팀 참여하기, 탈퇴하기 로직 수정
  app/(team-setting)/participate-team/_components/participate-team-form.tsx
  app/[groupId]/_components/member-list.tsx
  app/[groupId]/_components/modal/modal-member-delete.tsx
  lib/apis/type/index.ts
Labels: ♻️ refactor

#273 fix: 아이폰se까지 반응형 완료
  app/[groupId]/tasks/_components/comment/comment.tsx
  app/[groupId]/tasks/_components/comment/kebab-pop-over.tsx
  app/[groupId]/tasks/_components/modal/add-todo-modal/index.tsx
  app/[groupId]/tasks/_components/side-bar.tsx
  app/[groupId]/tasks/_components/todo/kebab-popover.tsx
Labels: ✨ feat

#275 refactor: 자유게시판 반응형 관련 스타일 개선
  app/(free-board)/_query/query.ts
  app/(free-board)/boards/[boardId]/_components/comments-list.tsx
  app/(free-board)/boards/_components/article-list/article-card.tsx
  app/(free-board)/boards/_components/article-list/articles-list.tsx
  app/(free-board)/boards/_components/article-ranking-chart.tsx
  utils/shorten-string.ts
Labels: ♻️ refactor

#278 fix: todoBox가 overflow되는 현상
  app/[groupId]/tasks/_components/todo/todo-contents.tsx
  app/[groupId]/tasks/page.tsx
Labels: 🐛 fix

#276 refactor: 사이드바 댓글 낙관적 업데이트 시도
  app/[groupId]/tasks/_components/comment/comment-input.tsx
  app/[groupId]/tasks/_components/side-bar.tsx
Labels: ♻️ refactor

#283 fix: priority 적용 및 사이드바 suffix 삭제, 에러 메세지 문구 수정
  app/(auth)/_components/easy-login-button.tsx
  app/(auth)/login/page.tsx
  app/(auth)/signup/page.tsx
  components/header/group-dropdown.tsx
  components/header/modal-side-menu.tsx
  components/input-field/password-input.tsx
  components/profile-input/profile-input.tsx
  public/icons/kakao-talk.svg
  public/images/landing-third.svg
  schemas/auth.ts
Labels: 🐛 fix

#281 refactor: 할 일 목록 클릭 시, 할 일 목록 id를 query로 전달 / admin 왕관 달아주기
  app/[groupId]/_components/member-list.tsx
  app/[groupId]/_components/modal/modal-member-profile.tsx
  app/[groupId]/_components/task-lists.tsx
Labels: ♻️ refactor, 💄design

#286 refactor: 자유게시판 이미지 관련 수정
  app/(free-board)/_components/card.tsx
  app/(free-board)/boards/[boardId]/_components/comments-list.tsx
  app/(free-board)/boards/_components/article-search-bar.tsx
Labels: ♻️ refactor

#294 refactor: task페이지 스크롤 굵기 수정
  app/[groupId]/tasks/_components/no-items/no-list.tsx
  app/[groupId]/tasks/_components/no-items/no-todo.tsx
  tailwind.config.ts
  utils/convert-date.ts
Labels: ♻️ refactor, 💄design

#284 fix: layout에 img height auto문제
  app/[groupId]/tasks/_components/todo/todo-list-name.tsx
  components/profile-Icon/profile-icon.tsx
Labels: 🐛 fix

#296 fix:노션 수정사항 및 긴급 버그 수정
  app/[groupId]/_components/member-list.tsx
  app/[groupId]/_components/modal/modal-member-delete.tsx
  app/[groupId]/_components/modal/modal-task-list-add.tsx
  app/[groupId]/_components/modal/modal-task-list-delete.tsx
  app/[groupId]/_components/modal/modal-task-list-name-edit.tsx
  app/[groupId]/_components/task-lists.tsx
  app/[groupId]/_components/task-report.tsx
  app/[groupId]/_components/team-name.tsx
  app/[groupId]/edit/_components/edit-team-form.tsx
  app/[groupId]/page.tsx
  app/[groupId]/tasks/_components/todo/todo-contents.tsx
  app/[groupId]/tasks/_components/todo/todo-contianer.tsx
  app/[groupId]/tasks/_components/todo/todo-header.tsx
  app/[groupId]/tasks/_hooks/use-calendar.ts
  app/[groupId]/tasks/_hooks/use-select-button.ts
  app/[groupId]/tasks/page.tsx
  lib/apis/task/hooks/use-edit-task.ts
  lib/apis/task/hooks/use-toggle-done-task.ts
  utils/convert-to-int.ts
Labels: ✨ feat, 🐛 fix

#291 fix: 이미지 길어지는 문제 수정
  app/[groupId]/_components/member-list.tsx
  app/[groupId]/_components/modal/modal-member-profile.tsx
  components/header/popover-trigger.tsx
  components/popover/popover.tsx
Labels: 🐛 fix

#299 fix: http를 https로 변환하는 커스텀 로더 추가
  my/image/loader.js
  next.config.mjs
  tsconfig.json
Labels: 🐛 fix

#301 fix: 로그인, 회원가입 로딩 처리 통일
  app/(auth)/signup/_components/signup-form.tsx
Labels: 🐛 fix
